version: '3'

services:

  prometheus:
    image: prometheus/cluster-local
    ports:
      - '9090:9090'
    deploy:
      mode: replicated
      replicas: 1
    placement:
      constraints:
        - node.role == manager
    network:
      - default
      
networks:
  default:
    external: true
      name: bridge
